In [94]:
import numpy as np

In [95]:
wines=np.genfromtxt('winequality-red.csv',delimiter=";",skip_header=1)

In [96]:
wines.size #size 

19188

In [97]:
wines.shape[0] #rows 

1599

In [98]:
wines.ndim #dimensions

2

In [99]:
type(wines) #type

numpy.ndarray

In [100]:
wines.dtype #data type

dtype('float64')

In [101]:
wines[:5, :] #top 5 rows

array([[7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00],
       [7.800e+00, 8.800e-01, 0.000e+00, 2.600e+00, 9.800e-02, 2.500e+01,
        6.700e+01, 9.968e-01, 3.200e+00, 6.800e-01, 9.800e+00, 5.000e+00],
       [7.800e+00, 7.600e-01, 4.000e-02, 2.300e+00, 9.200e-02, 1.500e+01,
        5.400e+01, 9.970e-01, 3.260e+00, 6.500e-01, 9.800e+00, 5.000e+00],
       [1.120e+01, 2.800e-01, 5.600e-01, 1.900e+00, 7.500e-02, 1.700e+01,
        6.000e+01, 9.980e-01, 3.160e+00, 5.800e-01, 9.800e+00, 6.000e+00],
       [7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00]])

In [102]:
wines[2,3] #3rd row 4th column

2.3

In [103]:
wines[:3,3] #3 items in 4th column

array([1.9, 2.6, 2.3])

In [104]:
wines[:,0] #1st column

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [105]:
wines[1,:]#2nd row

array([ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
        0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ])